config/routes.rb
Rails.application.routes.draw do
  root "application#welcome"
  get 'auth/:provider/callback', to: 'sessions#oauth'
  get "welcome", to: "application#welcome", as: "welcome"
  post "login", to: "application#login", as: "login"
  get "login", to: "application#login"
  post "signup", to: "users#signup", as: "signup"
  get "signup", to: "users#signup"
  patch "meals/:id", to: "meals#update"
  #get "order_again/:id", to: "deliveries#", as: "order_again"
  post "order_delivered/:id", to: "deliveries#completed", as: "order_delivered"
  get "logout", to: "sessions#destroy", as: "logout"
  get "delete/:id", to: "users#delete", as: "delete_user"
  get "hard_delete/:id", to: "users#hard_delete", as: "hard_delete"
  get "add_funds/:id", to: "users#add_funds", as: "add_funds"
  post "add_funds/:id", to: "users#funds_added"
  post "sessions/create", to: "sessions#create"
  post "users/:user_id/deliveries/:del_id/edit_user_delivery", to: "deliveries#payment_options"
  get "end_session", to: "application#end_session"
  get "fix_my_session", to: "application#fix_session"
  post "users/:id/deliveries/new_user_delivery", to: "deliveries#payment_options"
  post "guests/new", to: "guests#create", as: "new_guest"
  get "guests/deliveries/new", to: "deliveries#new", as: "guest_delivery"
  get "user/:user_id/delivery/:del_id/pay_with_credit", to: "deliveries#pay_with_credit", as: "pay_with_credit"
  get "user/delivery/:del_id/pay_with_cash", to: "deliveries#pay_with_cash", as: "pay_with_cash"
  get "delete/meal/:id", to: "meals#delete", as: "delete_admin_meal"
  post "meals", to: "meals#index", as: "filtered_meals"
  post "users/:user_id/meals/:meal_id/edit_user_delivery", to: "deliveries#payment_options"


  resources :users, only: [:new, :create, :edit, :update, :show] do
    resources :deliveries, only: [:index, :show, :new, :create, :edit, :update] # Index - Shows all your deliveries, seperated by delivered or not. New makes a new.... duh. Edit non-destructively makes a new one
    resources :meals, only: [:new, :create, :update, :create, :show, :edit]
  end
  resources :meals, only: [:index, :show]

  namespace :admin do
    resources :users
    resources :deliveries
    resources :meals
  end

end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
    
    has_many :deliveries
    has_many :meals, through: :deliveries
    has_many :items, through: :meals

    def isFilled(session)
        if (address == "" || name == "" || email == "" || password_digest == "")
            return false
        else
            return true
        end
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController 
    include ApplicationHelper

    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user.address = user_params[:address]
        @user.name = user_params[:name]
        @user.save
        binding.ory
    end

    def delete
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
    include ApplicationHelper
    skip_before_action :verify_authenticity_token, :only => [:funds_added]

    # essentially the 'new' action
    def signup
        @message = errorMsg(session)
        clearErrorMessage(session)
        @user = User.new # makes a new unsaved user for the form_for form 
    end

    # Creates new user, starting credit set to 0
    def create
        @user = User.new(user_params)
        if (@user.isFilled(session)) # Checks if the form was filled. If not it adds an error message 
            User.all.each do | sel | # This checks every other user in the user-verse
                if @user.email == sel.email # This checks if this new (not yet saved) user's email matches an existing user's email
                    addErrorMessage(session, "That email is already taken!") # This says yeeeeet (correct error message)
                    @user.delete # Gets rid of the lame user account
                    redirect_to signup_path # redirects 
                end
            end
            @user.credit = 0
            @user.save # Adds the new user to the databse
            clearErrorMessage(session) # Safety check, keeps session errors empty
            set_current_user(session, @user) # sets the current session 
            redirect_to user_path(@user) # send to the user show page
        else
            addErrorMessage(session, "Please Fill all Fields") #Adds the correct error message
            redirect_to signup_path # Sends back to signin, this time with session[:errors] occupied
        end
    end

    # lets a user see his/her own page only, unless admin
    def show
        session[:filter] = "none"
        @user = get_user
        if (isAdmin(session)) # Admins can see anyone
            clearErrorMessage(session)
        end
        if (@user.id != current_user(session).id) # You cannot see another user's page
            addErrorMessage(session, "You cannot view another user's page!") # correct error message
            redirect_to users_path(current_user(session)) # Redirects to your own
        else
            @message = errorMsg(session) # Sets up any error messages
            clearErrorMessage(session) # Resents the error queue
        end
    end

    # sets up confirmation screen if form submitted to this action
    def delete
        @user = get_user
        if (isAdmin(session))
            clearErrorMessage(session)
        elsif (@user != current_user(session)) # if the user id entered in the request does not match the id of the user currently logged in
            addErrorMessage(session, "You cannot delete someone else's account!") # correct error message
            redirect_to user_path(current_user(session)) 
        else
            #this opens the delete page which is a confirmation, does not yet actually delete
        end
    end

    # this ACTUALLY deletes a user
    def hard_delete   # This actually deletes the user. Only comes from delete.html.erb
        if (get_user == nil)
            redirect_to welcome_path
        end
        @user = get_user # finds the user
        if (current_user(session).admin || current_user(session) == User.find(params[:id]))
            if (isAdmin(session))
                @user.delete # deletes the user
                redirect_to user_path(current_user(session))
            else
                session[:user_id] = nil
                clearSession(session)
                @user.delete # deletes the user
                redirect_to welcome_path # sends you to welcome
            end
        else
            addErrorMessage(session, "Cannot delete other peoples' accounts!")
            redirect_to user_path(current_user(session))
        end
    end

    # duh
    def edit 
        @user = get_user
        redirect_if_invalid(session)
        @message = errorMsg(session)
    end

    # also duh
    def update
        if (isAdmin(session)) # admins can edit anyone
            @user = User.find(params[:id])
            @user.address = user_params[:address]
            @user.name = user_params[:name]
            @user.credit = user_params[:credit].to_f # admins can edit credit, normak users have to add credit from the home page
            @user.save
            clearErrorMessage(session)
        end
        @user = get_user
        if (@user.uid != nil)
            if (user_params[:new_password] != "" ) # changes password unless the form is left blank
                @user.password = user_params[:new_password]
            end
            @user.address = user_params[:address]
            @user.name = user_params[:name]
            @user.save
            clearErrorMessage(session)
            redirect_to user_path(@user)
        end
        if @user.authenticate(user_params[:password]) # to confirm changes, old password must be entered 
            if (user_params[:new_password] != "" ) # changes password unless the form is left blank
                @user.password = user_params[:new_password]
            end
            @user.address = user_params[:address]
            @user.name = user_params[:name]
            @user.save
            clearErrorMessage(session)
            redirect_to user_path(@user)
        else
            addErrorMessage(session, "You need to enter your previous password in order to change accounts details") # cannot edit other users
            redirect_to edit_user_path(@user)
        end
    end

    # this is how users add credit to their account
    def add_funds
        @user = get_user
        redirect_if_invalid(session)
        clearErrorMessage(session)
    end

    # this ACTUALLY adds the funds
    def funds_added
        @user = get_user
        @user.credit += user_params[:credit].to_f
        @user.save
        redirect_to user_path(@user)
    end


private

    def user_params
        params.require(:user).permit(:address, :name, :email, :password, :credit, :new_password)
    end

  #  def user_params(*args)
  #      params.require(:user).permit(*args)
  #  end

    def find_user
        return User.find(params[:id])
    end

end

app/helpers/user_helpers.rb
modulde UserHelpers

def isAdmin(session)
    if SessionHelpers.current_user(session).admin
        true
    else
        false
    end
end

def isGuest(session)
    if session[:guest]
        true
    else
        false
    end
end

end

app/views/users/add_funds.html.erb
<h1>Your Funds</h1>
<h3>Your Current Funds: <%= @user.credit %></h3>
<% if has_errors?(session) %>
  <p><%= @message %></p>
<% end %>
<form method= "post" action= "<%= @user.id %>">
  <input type= "text" name= "user[credit]">
  <input type= "submit" value= "Add">
</form>

app/views/users/delete.html.erb
<h1>Are you Sure you Want to Delete This Account?</h1>
<h2>
    <%= link_to "Yes", hard_delete_path(@user) %> || <%= link_to "No", user_path(@user) %> 
</h2>

app/views/users/edit.html.erb
<h1>Edit Your Account Information</h1>
<%= @message %>
<%= form_for @user do | f | %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :address %>
    <%= f.text_field :address %>
    <p>New Password (Optional): </p>
    <input type= "text" name= "user[new_password]">
    <br>
    <% if (@user.uid == nil) %>
        <p>Your old Password: </p>
        <%= f.password_field :password %>
        <br>
    <% end %>
    <%= f.submit "Edit" %>
<% end %>
<br>

<br>
<br>
<br>
<%= link_to "Return", user_path(@user) %>

app/views/users/show.html.erb
<h1><%= @user.name %>'s Customer Page!</h1>
<h4><%= @message %></h4>
<h3>Current Funds: <%= @user.credit %></h3>
<% if isAdmin(session) %>
  <h3>Admin Menu</h3>
  <p><%= link_to 'Edit/Delete Users', admin_users_path %></p>
  <p><%= link_to 'Edit/Delete Meals', admin_meals_path %></p>
<% end %>
<h5>--------------------------------------------------------------------------</h5>
<p> <strong>
  <%= link_to 'Edit Account', edit_user_path(@user) %> || <%= link_to 'Log Out', logout_path %> || <%= link_to 'Delete Account', delete_user_path(@user) %>
</strong> </p>
<p><strong><%= link_to "Add Funds", add_funds_path(@user) %></strong></p>
<h5>--------------------------------------------------------------------------</h5>
<h3>
  <%= link_to "Place New Order", new_user_delivery_path(@user) %>
  Or <%= link_to "Browse Existing Meals", meals_path %> from other users!
</h3>
<br>
<%= render partial: "deliveries/index", locals: {sel_user: @user} %>

app/views/users/signup.html.erb
<h1>Create a New Account!</h1>
<h3><%= @message %><h3>
<%= form_with model: @user do | f | %>
    <br>
    <%= f.label :username %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <br>
    <%= f.label :address %>
    <%= f.text_field :address %>
    <br> 
    <%= f.label :password %>
    <%= f.text_field :password %>
    <br>
    <%= f.submit %>
<% end %>